In [1]:
## import necessary libraries
import pandas as pd

In [2]:
df1 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/RawData/2023.csv')

In [3]:
df1

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2023-11-06 13:36:00,NaN,NaN,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Female,NaN,NaN,FORT SMITH ICE OFFICE,-,"ERO - Fort Smith, AR Sub Office",3 Other Immigration Violator,NaN,00003080dc4054b217a897a57ae274a7585563bd
1,2023-11-03 11:37:00,NaN,NaN,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-12-20 00:00:00,2016-04-09 00:00:00,STUART,NaN,"ERO - Stuart, FL Sub Office",1 Convicted Criminal,3.0,00038f76045b3d1bb8b62d85365e29a9924a58f1
2,2023-11-01 07:54:00,NaN,CALIFORNIA,NaN,Los Angeles Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-11-01 00:00:00,2017-07-02 00:00:00,VENTURA FUGITIVE OPERATIONS,-,"ERO - Ventura, CA Sub Office",1 Convicted Criminal,2.0,0003a23f3f22d9a40e269cf7401c551a29a88c24
3,2023-11-24 11:12:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,ACTIVE,...,COLOMBIA,Male,NaN,2024-06-20 00:00:00,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,3.0,0006989f31392d9aa50a51d46c451395b0547050
4,2023-11-01 11:42:00,NaN,TEXAS,NaN,San Antonio Area of Responsibility,ERO Criminal Alien Program,ICE,ERO Reprocessed Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,2024-10-10 00:00:00,WALKINS AT SAN ANTONIO,-,"ERO - San Antonio, TX Field Office",3 Other Immigration Violator,NaN,000732077b82caf319021e0154c64f9a77a6118e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29113,2023-12-29 07:02:06,NaN,NaN,NaN,NaN,Law Enforcement Area Response Units,ICE,Inspections,3 Other Immigration Violator,NaN,...,ALGERIA,Male,NaN,NaN,NaN,NaN,"DERBY LINE, VT (I-91), POE",NaN,NaN,NaN
29114,2023-12-29 12:34:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-12-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,NaN
29115,2023-12-29 12:13:49,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,MEXICO,Female,NaN,NaN,NaN,NaN,"DOUGLAS, AZ, POE",NaN,NaN,NaN
29116,2023-12-30 09:07:00,NaN,NaN,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
29117,2023-12-31 09:52:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-12-31 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [4]:
df23_state = df1["State"].value_counts()
df23_state

TEXAS                          5970
NEW YORK                       1991
FLORIDA                        1443
CALIFORNIA                     1260
NEW JERSEY                      658
GEORGIA                         575
LOUISIANA                       512
TENNESSEE                       429
ILLINOIS                        421
ARIZONA                         404
KENTUCKY                        384
INDIANA                         340
MASSACHUSETTS                   332
NORTH CAROLINA                  331
COLORADO                        330
VIRGINIA                        326
ALABAMA                         315
MISSISSIPPI                     307
OKLAHOMA                        300
OHIO                            273
SOUTH CAROLINA                  265
WASHINGTON                      263
MICHIGAN                        257
MARYLAND                        256
PENNSYLVANIA                    254
WISCONSIN                       249
UTAH                            248
MISSOURI                        215
MINNESOTA                       205
ARKANSAS                        204
KANSAS                          172
NEVADA                          135
IOWA                            105
NEBRASKA                         84
DELAWARE                         60
RHODE ISLAND                     58
PUERTO RICO                      58
CONNECTICUT                      52
WEST VIRGINIA                    45
OREGON                           34
MAINE                            29
NORTH DAKOTA                     20
NEW HAMPSHIRE                    19
WYOMING                          17
NEW MEXICO                       17
HAWAII                           12
IDAHO                            11
DISTRICT OF COLUMBIA             10
ALASKA                            9
VERMONT                           4
VIRGIN ISLANDS                    3
SOUTH DAKOTA                      3
NORTHERN MARIANA ISLANDS          3
GUAM                              2
ARMED FORCES - THE AMERICAS       1
MONTANA                           1
Name: State, dtype: int64

In [5]:
df23_state.to_csv('FilteredData/2023DeportationByState.csv', index=True)

In [6]:
df_NY = df1.query('State == "NEW YORK"') 
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
5,2023-10-02 09:26:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,2024-06-03 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00086086e4726f8d44c962916c4b6cfedc94963d
6,2023-11-18 12:28:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,0008a4e5a17cd75a53f3c0e905a6ecfd21ae4bea
37,2023-12-05 12:22:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,PERU,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,004cc6b2d9e1795339d0413005831b5b9c61e3bd
71,2023-12-12 11:52:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,2025-09-09 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0096e645ad04cd54b2009bceebfddb6a7c7b7ad2
78,2023-12-27 10:35:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,RUSSIA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00a42b3a329b38c0d1376df2dae2bc91cc2e834e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28626,2023-12-06 14:40:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Located,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Female,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",2 Pending Criminal Charges,NaN,fef1dc81fb1588f3d0479f8e2541176acb31939e
28670,2023-11-06 09:18:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ff5483b058ec55352b49429eebd16ff40c0f8a32
28681,2023-11-09 10:20:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,1 Convicted Criminal,ACTIVE,...,VENEZUELA,Male,NaN,2024-02-14 00:00:00,CAP - NASSAU COUNTY JAIL NY STATE,NaN,"ERO - Central Islip, NY Sub Office",1 Convicted Criminal,3.0,ff6ed8bd53247d7a72f585abc77536fe8530d775
28729,2023-12-22 07:17:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,EL SALVADOR,Male,2024-02-02 00:00:00,2024-01-12 00:00:00,WENDE CORRECTIONAL FACILITY,NaN,"ERO - Batavia, NY SPC Sub-Office",1 Convicted Criminal,1.0,ffd87d104e73203563c43797d090d34f78d663fe
28751,2023-12-13 12:42:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2025-04-30 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffffa86834be2a43223dc2e774417527b9962d69

In [7]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()
NYcounts

NDD - 26 FEDERAL PLAZA NY, NY                             1507
CIP GENERAL AREA, NON-SPECIFIC                             114
WENDE CORRECTIONAL FACILITY                                 76
SARATOGA COUNTY                                             59
FUGITIVE OPERATIONS NY STATE                                46
ERIE COUNTY                                                 33
NBG GENERAL AREA, NON-SPECIFIC                              22
FEDERAL CORRECTIONAL INSTITUTE RAY BROOK                    22
ONONDAGA COUNTY                                             17
CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE      15
CAP - BOP BROOKLYN NY STATE                                 14
JCART STREET ARREST NY STATE                                 8
CAP - NASSAU COUNTY JAIL NY STATE                            8
NON-DETAINED AND JUVENILE                                    6
MONROE COUNTY                                                6
NON-DETAINED and Juvenile                                    3
GENESEE COUNTY                                               3
ALBANY COUNTY                                                3
ICE ERO NEWARK                                               2
ONONDAGA COUNTY JAIL                                         2
ALBANY COUNTY JAIL                                           2
ORLEANS COUNTY                                               2
SCHENECTADY COUNTY JAIL                                      1
CAP - USM - SOUTHERN DISTRICT NY STATE                       1
CLINTON COUNTY                                               1
NEW GENERAL AREA, NON-SPECIFIC                               1
FRANKLIN COUNTY JAIL                                         1
ONTARIO COUNTY JAIL                                          1
CAP - WESTCHESTER COUNTY POLICE DEPARTMENT, NY STATE         1
BUFFALO GENERAL - Do Not Use                                 1
CAP - CITY OF POUGHKEEPSIE POLICE DEPARTMENT NY STATE        1
NEWARK CITY                                                  1
STUBEN COUNTY JAIL                                           1
CAP - PUTNAM COUNTY JAIL NY STATE                            1
CAYUGA COUNTY JAIL                                           1
CAP - SUFFOLK COUNTY JAIL NY STATE                           1
CAP - ORANGE COUNTY JAIL NY STATE                            1
CAP - USM - EASTERN DISTRICT NY State                        1
CAP - WESTCHESTER COUNTY JAIL NY STATE                       1
RENSSELAER COUNTY                                            1
At large arrest Suffolk County                               1
CAP - UNITED STATES PROBATION SDNY NY STATE                  1
ATD NY STATE                                                 1
Name: Apprehension Site Landmark, dtype: int64

In [8]:
NYcounts.to_csv('FilteredData/2023DeportationByNY.csv', index=True)

In [9]:
df_NY['Apprehension Site Landmark'].unique()

array(['SARATOGA COUNTY', 'NDD - 26 FEDERAL PLAZA NY, NY',
       'NBG GENERAL AREA, NON-SPECIFIC', 'ERIE COUNTY',
       'CIP GENERAL AREA, NON-SPECIFIC',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK',
       'WENDE CORRECTIONAL FACILITY',
       'CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE',
       'ONONDAGA COUNTY', 'FUGITIVE OPERATIONS NY STATE',
       'CAP - UNITED STATES PROBATION SDNY NY STATE',
       'At large arrest Suffolk County', 'RENSSELAER COUNTY',
       'CAP - BOP BROOKLYN NY STATE',
       'CAP - WESTCHESTER COUNTY JAIL NY STATE', 'ALBANY COUNTY',
       'JCART STREET ARREST NY STATE', 'ICE ERO NEWARK', 'MONROE COUNTY',
       'CAP - USM - EASTERN DISTRICT NY State',
       'CAP - ORANGE COUNTY JAIL NY STATE',
       'BUFFALO GENERAL - Do Not Use',
       'CAP - SUFFOLK COUNTY JAIL NY STATE', 'CAYUGA COUNTY JAIL',
       'CAP - PUTNAM COUNTY JAIL NY STATE', 'STUBEN COUNTY JAIL',
       'CAP - NASSAU COUNTY JAIL NY STATE', 'NEWARK CITY',
       'CAP - CITY OF POUGHKEEPSIE POLICE DEPARTMENT NY STATE',
       'NON-DETAINED AND JUVENILE', 'GENESEE COUNTY',
       'CAP - WESTCHESTER COUNTY POLICE DEPARTMENT, NY STATE',
       'FRANKLIN COUNTY JAIL', 'NEW GENERAL AREA, NON-SPECIFIC',
       'NON-DETAINED and Juvenile', 'ALBANY COUNTY JAIL',
       'SCHENECTADY COUNTY JAIL', 'ONONDAGA COUNTY JAIL',
       'ORLEANS COUNTY', 'CAP - USM - SOUTHERN DISTRICT NY STATE',
       'CLINTON COUNTY', 'ONTARIO COUNTY JAIL', 'ATD NY STATE'],
      dtype=object)

In [10]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [11]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]

In [12]:
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
5,2023-10-02 09:26:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,2024-06-03 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,00086086e4726f8d44c962916c4b6cfedc94963d
933,2023-10-16 09:50:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,2025-10-30 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,08c1afdb03971ae038ea1b42e91256e14ef31260
1327,2023-10-13 11:47:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Probation and Parole,1 Convicted Criminal,6-Deported/Removed - Deportability,...,JAMAICA,Male,2023-12-21 00:00:00,2023-11-07 00:00:00,RENSSELAER COUNTY,-,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,2.0,0c2d57ba9ede26b36f43b72df5bfc9bc4955c689
1917,2023-10-19 09:21:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,AFGHANISTAN,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,11a0c48d90b3ad55e1d28983965e1b27aea209fb
2306,2023-10-01 13:59:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,ACTIVE,...,VENEZUELA,Male,NaN,2025-08-13 00:00:00,ALBANY COUNTY,-,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,14d7040a1ae3d8c44c755db00ab8001b55ccb07e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25930,2023-10-17 11:14:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,CUBA,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,e704df8ee3885e80aa5b89fcee4b6ee986b99590
26841,2023-11-07 10:03:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-12-07 00:00:00,2025-11-24 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,eeda15e05a188d30d1944ad69bf8563d87ed81c4
27226,2023-10-19 09:26:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,AFGHANISTAN,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f248ffd74ed764022224a56c6ab42674044f9403
28152,2023-12-14 11:17:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,NICARAGUA,Male,2024-03-07 00:00:00,2023-12-12 00:00:00,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,faeb8ccfa2106eaaf202f24c375753ff96a45b0d
28589,2023-10-19 14:13:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VIETNAM,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fe8a2a1517a37e14c71ee6f84d70c57553e99e07

In [13]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY            59
ALBANY COUNTY               3
RENSSELAER COUNTY           1
SCHENECTADY COUNTY JAIL     1
Name: Apprehension Site Landmark, dtype: int64

In [14]:
df_CR.to_csv('FilteredData/2023CapitalRegionICEArrests.csv', index = True)