In [35]:
## import necessary libraries
import pandas as pd

In [36]:
df1 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/FilteredData/2024pt1.csv')

In [37]:
df1

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2024-12-16 15:20:00,NaN,KENTUCKY,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2025-01-13 00:00:00,2024-04-09 00:00:00,"FAYETTE COUNTY CORRECTIONS, KY",NaN,"ERO - Louisville, KY Sub-Office",1 Convicted Criminal,2.0,00055443836e80ce1995636703655b48c3997ee0
1,2024-10-15 16:32:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2024-11-09 00:00:00,2024-11-07 00:00:00,"EDN GENERAL AREA, NON-SPECIFIC",-,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,2.0,0008e4b572f8efd6e5c437802c3085c91035cda6
2,2024-11-04 09:34:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2025-05-09 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0009f9ba7cc635f7620fd6d2b0be86f968c04d71
3,2024-12-16 11:43:00,NaN,ILLINOIS,NaN,Chicago Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,HONDURAS,Male,2024-12-24 00:00:00,2015-03-25 00:00:00,US Penitentiary Thomson,NaN,"ERO - Rock Island, IL Sub-Office",1 Convicted Criminal,1.0,000b420c1f9a857ad7570b77a7a1d26ceb27b0c3
4,2024-10-02 12:13:00,NaN,KENTUCKY,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Other efforts,3 Other Immigration Violator,ACTIVE,...,MEXICO,Female,NaN,NaN,"ERO LOUISVILLE, KY SUB OFFICE",-,"ERO - Louisville, KY Sub-Office",3 Other Immigration Violator,NaN,0014ebcc385aa1e7ea3fc8d3762ef9076e8618d6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26498,2024-12-30 09:56:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-12-30 00:00:00,NaN,"HIDALGO COUNTY JAIL, EDINBURG, TXN - TX1080000",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
26499,2024-12-30 10:41:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-12-30 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Laredo, TX Detention Center",2 Pending Criminal Charges,NaN,NaN
26500,2024-12-30 10:46:15,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"SAN YSIDRO, CA, POE",NaN,NaN,NaN
26501,2024-12-30 14:03:00,NaN,ARKANSAS,NaN,New Orleans Area of Responsibility,287G Program,ICE,287(g) Program,3 Other Immigration Violator,NaN,...,EL SALVADOR,Male,NaN,NaN,Benton County Jail 287(g),HQ Tracking of Processing done by 287(g) autho...,Benton County Sheriff's Office,NaN,NaN,NaN
26502,2024-12-30 15:06:00,NaN,LOUISIANA,NaN,New Orleans Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HONDURAS,Male,NaN,NaN,Shreveport RAC,NaN,"ERO - Shreveport, LA Sub-Office",3 Other Immigration Violator,NaN,NaN

In [24]:
df24_state = df1["State"].value_counts()
df24_state

TEXAS                          5395
FLORIDA                        1922
CALIFORNIA                     1327
NEW JERSEY                      755
LOUISIANA                       692
NEW YORK                        666
ALABAMA                         653
GEORGIA                         637
TENNESSEE                       625
ARIZONA                         583
VIRGINIA                        438
OKLAHOMA                        430
PENNSYLVANIA                    416
KENTUCKY                        414
INDIANA                         408
ARKANSAS                        398
NORTH CAROLINA                  393
MISSISSIPPI                     390
SOUTH CAROLINA                  329
MARYLAND                        327
MASSACHUSETTS                   312
ILLINOIS                        308
UTAH                            303
COLORADO                        294
MISSOURI                        230
MICHIGAN                        217
MINNESOTA                       200
KANSAS                          182
OHIO                            181
WISCONSIN                       154
WASHINGTON                      133
NEVADA                          113
NEBRASKA                        101
NEW MEXICO                       83
IOWA                             75
PUERTO RICO                      69
DELAWARE                         55
RHODE ISLAND                     53
WYOMING                          50
CONNECTICUT                      49
WEST VIRGINIA                    37
MAINE                            28
NEW HAMPSHIRE                    23
VIRGIN ISLANDS                   23
OREGON                           20
SOUTH DAKOTA                     19
IDAHO                            17
NORTH DAKOTA                     10
NORTHERN MARIANA ISLANDS          7
DISTRICT OF COLUMBIA              7
HAWAII                            6
ALASKA                            5
GUAM                              4
ARMED FORCES - THE AMERICAS       3
VERMONT                           1
MONTANA                           1
ARMED FORCES - EUROPE             1
Name: State, dtype: int64

In [25]:
df24_state.to_csv('FilteredData/2024DeportationByState.csv', index=True)

In [26]:
df_NY = df1.query('State == "NEW YORK"') 
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
2,2024-11-04 09:34:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2025-05-09 00:00:00,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0009f9ba7cc635f7620fd6d2b0be86f968c04d71
29,2024-12-02 13:37:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,003f2571392242493fff11809895f4d3f3c8c427
30,2024-11-18 06:32:07,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Male,2024-12-09 00:00:00,2024-06-27 00:00:00,WENDE CORRECTIONAL FACILITY,NaN,BATAVIA CMD CTR NY DCO,1 Convicted Criminal,1.0,004341d68d9fd5e5c714ac7ba5fb215366f26946
47,2024-12-09 18:44:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,ACTIVE,...,KUWAIT,Male,NaN,2003-12-22 00:00:00,ONONDAGA COUNTY JAIL,NaN,"ERO - Syracuse, NY Sub-Office",1 Convicted Criminal,1.0,0062d4cc5922d7575d5279105f13a80f16292268
121,2024-10-21 14:10:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0124e287c6350cb88305a1b038cb9ee7a35f730e
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26201,2024-12-13 08:30:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Federal Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-12-23 00:00:00,2013-03-04 00:00:00,FEDERAL CORRECTIONAL INSTITUTE RAY BROOK,NaN,"ERO - Champlain, NY Sub-Office",1 Convicted Criminal,1.0,ff57ea6944d6e3db386b5f9d22211ca2a2551a34
26245,2024-10-25 07:24:11,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,COLOMBIA,Male,2024-11-25 00:00:00,2024-06-21 00:00:00,WENDE CORRECTIONAL FACILITY,NaN,BATAVIA CMD CTR NY DCO,1 Convicted Criminal,1.0,ffc92b9a42788598697ea85bc8c22a536aa8bc86
26249,2024-11-26 10:25:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffd0a2133e2dd2d3f10ab7f88fb8f8c1d1e7f64c
26251,2024-10-29 10:30:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffd133e396783c38350dcbe14b2eec119e879944
26255,2024-10-22 09:48:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffe53b733d40795924c8fdacfb7ef19dc51f6411

In [27]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()
NYcounts

NDD - 26 FEDERAL PLAZA NY, NY                             338
WENDE CORRECTIONAL FACILITY                               101
SARATOGA COUNTY                                            33
CIP GENERAL AREA, NON-SPECIFIC                             32
NBG GENERAL AREA, NON-SPECIFIC                             21
FUGITIVE OPERATIONS NY STATE                               18
ERIE COUNTY                                                14
CAP - NASSAU COUNTY JAIL NY STATE                          14
FEDERAL CORRECTIONAL INSTITUTE RAY BROOK                   11
CAP - BOP BROOKLYN NY STATE                                 8
ICE ERO NEWARK                                              7
ONONDAGA COUNTY                                             5
ALBANY COUNTY JAIL                                          5
NON-DETAINED and Juvenile                                   4
ALBANY COUNTY                                               4
CAP - USM - SOUTHERN DISTRICT NY STATE                      3
FOS GENERAL AREA, NON-SPECIFIC                              3
SCHENECTADY COUNTY                                          2
CLINTON COUNTY                                              2
JCART STREET ARREST NY STATE                                2
CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE      2
FRANKLIN COUNTY                                             2
ERIE COUNTY JAIL                                            2
CAP - ORANGE COUNTY JAIL NY STATE                           2
CAP - ULSTER CORRECTIONAL FACILITY NY STATE                 2
ATD NY STATE                                                2
MONROE COUNTY                                               2
ELP GENERAL AREA, NON-SPECIFIC                              1
BROOME COUNTY JAIL                                          1
At large arrest Suffolk County                              1
FULTON COUNTY                                               1
BOP BROOKLYN                                                1
VCAS - QUEENS CENTRAL BOOKING, NY STATE                     1
CAP - BEDFORD CORRECTIONAL FACILITY NY STATE                1
DELAWARE COUNTY JAIL                                        1
SCHENECTADY COUNTY JAIL                                     1
HERKIMER COUNTY                                             1
CHENANGO COUNTY JAIL                                        1
WAYNE COUNTY JAIL                                           1
ONONDAGA COUNTY JAIL                                        1
ONTARIO COUNTY JAIL                                         1
OTSEGO COUNTY                                               1
ORLEANS COUNTY                                              1
CLINTON COUNTY JAIL                                         1
SARATOGA COUNTY JAIL                                        1
WASHINGTON COUNTY                                           1
ONTARIO COUNTY                                              1
NON-DETAINED AND JUVENILE                                   1
ALB GENERAL AREA, NON-SPECIFIC                              1
CAP - SUFFOLK COUNTY JAIL NY STATE                          1
VCAS-FACILITY ARREST NY                                     1
CAP - QUEENSBORO CORRECTIONAL FACILITY NY STATE             1
Name: Apprehension Site Landmark, dtype: int64

In [28]:
NYcounts.to_csv('FilteredData/2024DeportationByNY.csv', index=True)

In [29]:
df_NY['Apprehension Site Landmark'].unique()

array(['NDD - 26 FEDERAL PLAZA NY, NY', 'WENDE CORRECTIONAL FACILITY',
       'ONONDAGA COUNTY JAIL', 'NBG GENERAL AREA, NON-SPECIFIC',
       'ALBANY COUNTY', 'ERIE COUNTY', 'SARATOGA COUNTY',
       'CIP GENERAL AREA, NON-SPECIFIC', 'CAP - BOP BROOKLYN NY STATE',
       'FOS GENERAL AREA, NON-SPECIFIC',
       'CAP - NASSAU COUNTY JAIL NY STATE', 'ORLEANS COUNTY',
       'NON-DETAINED and Juvenile', 'FUGITIVE OPERATIONS NY STATE',
       'CAP - USM - SOUTHERN DISTRICT NY STATE', 'MONROE COUNTY',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK',
       'ALB GENERAL AREA, NON-SPECIFIC', 'ONONDAGA COUNTY',
       'ICE ERO NEWARK', 'ATD NY STATE',
       'CAP - ULSTER CORRECTIONAL FACILITY NY STATE', 'OTSEGO COUNTY',
       'ELP GENERAL AREA, NON-SPECIFIC', 'CLINTON COUNTY',
       'ALBANY COUNTY JAIL', 'CAP - ORANGE COUNTY JAIL NY STATE',
       'VCAS-FACILITY ARREST NY', 'CAP - SUFFOLK COUNTY JAIL NY STATE',
       'CAP - OTISVILLE FEDERAL CORRECTIONAL FACILITY NY STATE',
       'JCART STREET ARREST NY STATE', 'NON-DETAINED AND JUVENILE',
       'ONTARIO COUNTY', 'WASHINGTON COUNTY', 'SCHENECTADY COUNTY',
       'SARATOGA COUNTY JAIL', 'CLINTON COUNTY JAIL', 'ERIE COUNTY JAIL',
       'FRANKLIN COUNTY', 'ONTARIO COUNTY JAIL', 'BROOME COUNTY JAIL',
       'WAYNE COUNTY JAIL', 'CHENANGO COUNTY JAIL', 'HERKIMER COUNTY',
       'SCHENECTADY COUNTY JAIL', 'DELAWARE COUNTY JAIL',
       'CAP - BEDFORD CORRECTIONAL FACILITY NY STATE',
       'VCAS - QUEENS CENTRAL BOOKING, NY STATE', 'BOP BROOKLYN',
       'FULTON COUNTY', 'At large arrest Suffolk County',
       'CAP - QUEENSBORO CORRECTIONAL FACILITY NY STATE'], dtype=object)

In [30]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [31]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]

In [33]:
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
200,2024-10-21 11:19:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Female,2026-01-15 00:00:00,2024-02-07 00:00:00,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,01db17dc0a64600d071f6cd8b5c06f9dd97d36b6
225,2024-11-12 10:50:25,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Female,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,0221b9521a2480eb446d18a2d540706203343377
468,2024-12-13 10:56:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,0479f51adcde15374dc83506d8b223bb07576c3f
1271,2024-10-02 11:09:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,2 Pending Criminal Charges,ACTIVE,...,COLOMBIA,Male,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,0c33252c8b745a8b14c1c27c52b0d460e5c3e230
2533,2024-12-13 11:31:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,BRAZIL,Female,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,1832a62c123feb14e4a2871b5042c36a261cc330
3100,2024-11-20 17:53:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,BRAZIL,Male,2025-01-10 00:00:00,2023-11-08 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,1da744d7a57fa917979fa8e05ab33b5310f357c3
3912,2024-10-11 12:28:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,2562ce565f1ce3a63ef6984d4de1e6ff734b3ea9
4199,2024-11-06 09:34:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,281f751bd2670876d9f406393773569b5f3a28a8
4252,2024-10-21 12:40:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Female,2026-01-15 00:00:00,2024-02-07 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,28bc88e5a7782716e228b795bfba3f22736bf62e
5147,2024-10-28 11:41:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,2024-07-11 00:00:00,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,31548852c875daf046c1c0eae7d3dabea8db1a72
7108,2024-11-02 10:25:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,3-Voluntary Departure Confirmed,...,"CHINA, PEOPLES REPUBLIC OF",Male,2024-12-25 00:00:00,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,451bd0f2c906666af204616c642e2bdcd24834be
7536,2024-10-28 10:38:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,496747d9b40890107070e4c696ea179588eb7c17
8410,2024-10-25 12:06:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,A-Proceedings Terminated,...,PAKISTAN,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,52eb57036ef9d8a3e01b785c3837c85e755460a6
8780,2024-10-28 12:00:35,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2024-07-11 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,56ace15efc1aba9d24c4a915dc26b7ea31dd7bb4
11747,2024-10-17 09:41:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,INDIA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,7363510ed30b1f65c42420bca8e3de5bc712d2a3
12408,2024-12-19 11:23:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,MEXICO,Female,2025-05-07 00:00:00,2024-08-28 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,79b88a5357e0faa081b878ba104636172eb9930c
12476,2024-12-10 09:59:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2025-08-26 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,7a5abb655a28e23c37263b597b7333813b320f56
13057,2024-12-04 12:09:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,Located,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,7f84732b4aff40216ae90a53e5aa3f28f573cedc
13287,2024-12-19 11:21:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2025-05-07 00:00:00,2024-08-28 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,81c6ff921d95eef3477431c6386f58af9534bd4f
13538,2024-10-24 00:00:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-12-30 00:00:00,2019-10-27 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,1.0,841305f0ef5e214276c5bee20a06207c231aad63
14007,2024-10-28 09:34:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,2024-10-09 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,88b7d4d5041a1e907e36f749aeb6ef96ba3fbb5a
14771,2024-10-30 09:44:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Female,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,902d585ddcf20cc1e4dabe4618b8b679e8dda1b4
16883,2024-10-31 12:24:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,a57d480f942ab402399e7e866c0a44d6d97ad457
17348,2024-11-21 20:46:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,INDIA,Male,2025-04-28 00:00:00,2025-01-06 00:00:00,SARATOGA COUNTY JAIL,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,a9f86ddcb279c541c4ed0fd4b6769e77a1c11780
17589,2024-10-28 12:06:05,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,2024-07-11 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,ac8d75d0e4a0f2d56167484ecffab32382eefa1e
17821,2024-11-26 14:16:40,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,ACTIVE,...,VENEZUELA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,ae9cf307381a9496cba674c55233a184727fbcbe
18592,2024-11-13 10:56:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,EL SALVADOR,Female,NaN,2023-12-20 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,b5b4212e58138532dcac34ae6f8d14056562827e
19661,2024-11-12 11:24:13,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,PERU,Male,2025-04-22 00:00:00,2024-08-21 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,c04940fc92861f4e7d65a3f4427c027379123964
19816,2024-10-29 10:49:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2024-12-09 00:00:00,2024-08-13 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,c20abb56f87346a4cb0f96694687d947b99d9719
20259,2024-12-20 12:04:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,BRAZIL,Male,2025-04-10 00:00:00,2024-11-22 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,c684776eb1067bc47b095db60075576474af9317
20519,2024-12-10 10:24:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Male,2025-05-27 00:00:00,2025-05-15 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,c8fd70d1fe908616221fa1b946ba5a71d3038a06
21154,2024-12-18 18:02:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,ST. LUCIA,Male,2025-05-24 00:00:00,2025-02-22 00:00:00,SCHENECTADY COUNTY JAIL,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,cfaf68d000b522dbeabda2e83a8aaf2696397730
21420,2024-10-29 18:00:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,ACTIVE,...,COLOMBIA,Male,NaN,2023-08-22 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",2 Pending Criminal Charges,NaN,d203302e0ca876e7d025ff5bd82a015a19110d81
21472,2024-10-18 10:31:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,TURKIYE,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,d280803d6b5880b37bee4a78a70d862bef46648e
22349,2024-12-19 11:22:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,MEXICO,Female,2025-05-07 00:00:00,2024-08-28 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,dae430f628956a83921acd28d2edc2737c527cd8
22894,2024-10-11 12:46:46,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Non-Detained Docket Control,ICE,Located,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,e04391e775f1ed0fec90dd336eab2c97ec7873e7
23044,2024-12-04 11:07:09,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Female,NaN,2025-12-17 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,e185ddd2a8eb6663ee9fca5e8d0e8656da8f2560
23814,2024-10-21 12:52:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Located,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Male,2026-01-15 00:00:00,2024-02-07 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,e88d5f9d2ae37b6e375bc0833895d5cb0e9c204a
24243,2024-10-07 11:25:00,NaN,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,SARATOGA COUNTY,-,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,ecf4c2f63601812e0c6abe7376fe8b5fb178d282

In [34]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY            33
ALBANY COUNTY               4
SARATOGA COUNTY JAIL        1
SCHENECTADY COUNTY JAIL     1
Name: Apprehension Site Landmark, dtype: int64

In [16]:
df_CR.to_csv('FilteredData/2023CapitalRegionICEArrests.csv', index = True)