In [1]:
## import necessary libraries
import pandas as pd

In [2]:
df1 = pd.read_csv('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/ICEarrests-Albany/FilteredData/2026.csv')

In [3]:
df1

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2026-02-14 10:27:08,Targeted,FLORIDA,NaN,Miami Area of Responsibility,ERO Criminal Alien Program,ICE,287(g) Program,2 Pending Criminal Charges,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"FMY GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Fort Myers, FL Sub Office",2 Pending Criminal Charges,NaN,0001c9598ba1c9866270b617f4c82ff2e04d3e29
1,2026-01-28 07:21:16,Targeted,PENNSYLVANIA,NaN,Philadelphia Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Male,NaN,NaN,Fugitive Operations Cumberland County,NaN,"ERO - YORK, PA SUB-OFFICE",3 Other Immigration Violator,NaN,000320f91e2cc9fe2fb94e9b2290ac95b406ed51
2,2026-02-09 11:52:30,Targeted,TENNESSEE,NaN,New Orleans Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Male,NaN,NaN,"MEM GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Memphis, TN Sub Office",3 Other Immigration Violator,NaN,0003b1570cd8fe448fc9482fc5f662a232096e4d
3,2026-02-20 17:20:00,Collateral,NORTH CAROLINA,NaN,Atlanta Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"WIL GENERAL AREA, NON-SPECIFIC",-,"ERO - Wilmington, NC Sub Office",3 Other Immigration Violator,NaN,000401e817c1ade412991c8d19023da09845473b
4,2026-02-26 18:30:15,NaN,NaN,NaN,Chicago Area of Responsibility,Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Male,NaN,2026-02-26 00:00:00,NaN,NaN,"CHICAGO, IL, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0005582db22620e160633fb3cc6448cb143709e1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79600,2026-03-10 17:07:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
79601,2026-03-10 17:22:39,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
79602,2026-03-10 17:21:11,Collateral,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Non-Custodial Arrest,3 Other Immigration Violator,9-VR Witnessed,...,MEXICO,Male,2026-03-10 00:00:00,NaN,"LRD GENERAL AREA, NON-SPECIFIC",---,"ERO - Laredo, TX Detention Center",3 Other Immigration Violator,NaN,NaN
79603,2026-03-10 16:14:39,Collateral,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,MEXICO,Male,NaN,NaN,RAINS COUNTY CRIM AT LARGE,NaN,"DALLAS EAST, MCAT",NaN,NaN,NaN
79604,2026-03-10 18:26:43,NaN,NaN,NaN,Chicago Area of Responsibility,Non-Detained Docket Control,ICE,Inspections,3 Other Immigration Violator,NaN,...,COLOMBIA,Female,NaN,NaN,NaN,NaN,"CHICAGO-O'HARE INTERNATIONAL AIRPORT, CHICAGO ...",NaN,NaN,NaN

In [4]:
df26_state = df1["State"].value_counts()

In [5]:
df26_state

TEXAS                             18887
FLORIDA                            7551
CALIFORNIA                         6706
MINNESOTA                          3233
NEW YORK                           3056
GEORGIA                            2919
NEW JERSEY                         2673
ARIZONA                            2446
VIRGINIA                           2050
TENNESSEE                          2003
ALABAMA                            1817
MARYLAND                           1813
PENNSYLVANIA                       1694
NORTH CAROLINA                     1489
OKLAHOMA                           1346
NEW MEXICO                         1161
INDIANA                            1154
MASSACHUSETTS                      1138
LOUISIANA                          1136
MICHIGAN                           1089
OHIO                               1045
SOUTH CAROLINA                      999
WEST VIRGINIA                       990
UTAH                                927
COLORADO                            839
MISSOURI                            801
WASHINGTON                          751
MISSISSIPPI                         684
ARKANSAS                            665
ILLINOIS                            635
KENTUCKY                            571
NEVADA                              532
KANSAS                              458
NEBRASKA                            429
WISCONSIN                           389
IOWA                                374
WYOMING                             290
IDAHO                               286
MAINE                               247
OREGON                              169
SOUTH DAKOTA                        167
CONNECTICUT                         153
DELAWARE                            137
PUERTO RICO                         123
NEW HAMPSHIRE                        76
RHODE ISLAND                         59
NORTH DAKOTA                         56
DISTRICT OF COLUMBIA                 38
HAWAII                               37
MONTANA                              37
VIRGIN ISLANDS                       26
ALASKA                               26
NORTHERN MARIANA ISLANDS             20
VERMONT                              13
GUAM                                 11
ARMED FORCES - THE AMERICAS           9
FEDERATED STATES OF MICRONESIA        3
CHIAPAS                               1
OTHER                                 1
ARMED SERVICES - PACIFIC              1
Name: State, dtype: int64

In [6]:
df26_state.to_csv('FilteredData/2026DeportationByState.csv', index=True)

In [9]:
df_NY = df1.query('State == "NEW YORK"') 
df_NY

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
31,2026-02-01 07:20:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,GUATEMALA,Male,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,00207ed8ce88e501fabf53b98ff0357203f83678
37,2026-02-15 08:14:02,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Alternatives to Detention,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Male,NaN,NaN,ATD NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,0022b81e54e4f3ce36acd77d2a89b44156ddd567
50,2026-02-06 08:44:16,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,0032442e66899c8db1af57d2421d5fe8285525d4
73,2026-01-22 09:00:00,Collateral,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Male,2026-02-23 00:00:00,2026-01-22 00:00:00,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,0049aa0ba35cea8f3a2a2871531f2f130a65fb1c
84,2026-01-10 11:18:00,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,3-Voluntary Departure Confirmed,...,MEXICO,Male,2026-01-29 00:00:00,NaN,ONONDAGA COUNTY,NaN,"ERO - Syracuse, NY Sub-Office",2 Pending Criminal Charges,NaN,0051fccc72b13fe407b62d7ef7a4846615436007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77312,2026-03-05 10:47:04,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Alternatives to Detention,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,NaN,ATD NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffc9a5f6aebbaa12a5c105fe7a32c7c498ece9d4
77319,2026-02-13 10:28:48,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Alternatives to Detention,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,NaN,ATD NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffcfc0c1401746d98c61f7d38564087ff80904de
77343,2026-02-03 09:01:13,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HONDURAS,Male,NaN,NaN,"CIP GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Central Islip, NY Sub Office",3 Other Immigration Violator,NaN,ffde9ccb91d5cd952a10cf214fc0d2123215cebc
77346,2026-02-02 12:44:50,Targeted,NEW YORK,NaN,New York City Area of Responsibility,Alternatives to Detention,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,COLOMBIA,Female,NaN,NaN,ATD NY STATE,NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,ffdfdb912f25b3f36b77abdd09727d23771038fe
77371,2026-02-25 14:45:24,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Male,NaN,NaN,MONROE COUNTY,NaN,BATAVIA CMD CTR NY DCO,3 Other Immigration Violator,NaN,fff60d55ebf43ae7f0f3988a2157581ccced2303

In [10]:
NYcounts = df_NY['Apprehension Site Landmark'].value_counts()
NYcounts

CIP GENERAL AREA, NON-SPECIFIC        692
ATD NY STATE                          518
NDD - 26 FEDERAL PLAZA NY, NY         260
HAR GENERAL AREA, NON-SPECIFIC        240
FUGITIVE OPERATIONS NY STATE          222
                                     ...
GRM GENERAL AREA, NON-SPECIFIC          1
WAYNE COUNTY                            1
BROOME COUNTY                           1
BUFFALO FEDERAL DETENTION FACILITY      1
GREEN HAVEN CORRECTIONAL FACILITY       1
Name: Apprehension Site Landmark, Length: 87, dtype: int64

In [11]:
NYcounts.to_csv('FilteredData/2026DeportationByNY.csv', index=True)

In [12]:
df_NY['Apprehension Site Landmark'].unique()

array(['CIP GENERAL AREA, NON-SPECIFIC', 'ATD NY STATE', 'ALBANY COUNTY',
       'ONONDAGA COUNTY', 'NDD - 26 FEDERAL PLAZA NY, NY',
       'FUGITIVE OPERATIONS NY STATE', 'MONROE COUNTY',
       'NBG GENERAL AREA, NON-SPECIFIC', 'ERIE COUNTY', 'CHAMPLAIN POE',
       'PRO FUGOPS', 'WENDE CORRECTIONAL FACILITY', 'SARATOGA COUNTY',
       'ONEIDA COUNTY', 'TIOGA COUNTY', 'HAR GENERAL AREA, NON-SPECIFIC',
       'RENSSELAER COUNTY', 'FUG OPS CT', 'MONTGOMERY COUNTY',
       'LEWISTON BRIDGE POE', 'ATD MA STATE', 'SCHENECTADY COUNTY',
       'PEACE BRIDGE POE', 'FRANKLIN COUNTY',
       'PIT GENERAL AREA, NON-SPECIFIC', 'COLUMBIA COUNTY',
       'GENESEE COUNTY', 'OSWEGO COUNTY', 'STUEBEN COUNTY',
       'HARTFORD, CT', 'MADISON COUNTY JAIL',
       'COXSACKIE CORRECTIONAL FACILITY', 'RAINBOW BRIDGE POE',
       'CLINTON COUNTY', 'WASHINGTON COUNTY', 'NIAGARA COUNTY',
       'FEDERAL CORRECTIONAL INSTITUTE RAY BROOK',
       'GRM GENERAL AREA, NON-SPECIFIC',
       'CAP - ORANGE COUNTY PROBATION  NY STATE',
       'FUGITIVE OPERATIONS NY State', 'SCHENECTADY COUNTY JAIL',
       'FISHKILL CORRECTIONAL FACILITY', 'CAP - BOP BROOKLYN NY STATE',
       'ONONDAGA COUNTY JAIL', 'SCHOHARIE COUNTY',
       'CAP - ORANGE COUNTY JAIL NY STATE',
       'CAP - ROCKLAND COUNTY JAIL NY STATE',
       'ALBION CORRECTIONAL FACILITY', 'BOP BROOKLYN', 'ORLEANS COUNTY',
       'ONTARIO COUNTY', 'ESSEX COUNTY', 'LIVINGSTON COUNTY JAIL',
       'DELAWARE COUNTY',
       'CAP - WOODBURY TOWN POLICE DEPARTMENT, NY STATE',
       'WASHINGTON COUNTY JAIL', 'CAP - USM - SOUTHERN DISTRICT NY STATE',
       'MARCY CORRECTIONAL FACILITY',
       'CAP - ULSTER CORRECTIONAL FACILITY NY STATE', 'WARREN COUNTY',
       'ALBANY COUNTY JAIL', 'Nassau County Jail',
       'At large arrest Nassau County', 'WAYNE COUNTY', 'BROOME COUNTY',
       'BUFFALO FEDERAL DETENTION FACILITY', 'TIOGA COUNTY JAIL',
       'ULSTER CORRECTIONAL FACILITY', 'NEWARK PD', 'HUDSON COUNTY JAIL',
       'NON-DETAINED AND JUVENILE', 'CORTLAND COUNTY JAIL',
       'WYOMING COUNTY JAIL', 'CHEMUNG COUNTY', 'LONG BRANCH PD',
       'CATTARAUGUS COUNTY', 'SHAWANGUNK CORRECTIONAL FACILITY',
       'MONROE COUNTY JAIL', 'CAP - PUTNAM COUNTY PROBATION  NY STATE',
       'SENECA COUNTY', 'CAP - WHITE PLAINS CITY POLICE NY STATE',
       'OTSEGO COUNTY', 'CAP - FALLSBURG POLICE DEPARTMENT NY STATE',
       'CAP - RMSC - ROSE M. SINGER CENTER NY STATE', 'CHAUTAUQUA COUNTY',
       'ONEIDA COUNTY JAIL', 'GREEN HAVEN CORRECTIONAL FACILITY'],
      dtype=object)

In [13]:
CapitalRegion= ['ALBANY COUNTY','RENSSELAER COUNTY', 'SARATOGA COUNTY', 'GREENE COUNTY', 'WARREN COUNTY', 'WARREN COUNTY JAIL', 'SCHENECTADY COUNTY JAIL', 'SARATOGA COUNTY JAIL', 'RENSSELAER COUNTY JAIL', 'WASHINGTON CORRECTIONAL FACILITY', 'WASHINGTON COUNTY JAIL']

In [14]:
df_CR = df_NY[df_NY['Apprehension Site Landmark'].isin(CapitalRegion)]

In [15]:
df_CR

,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
50,2026-02-06 08:44:16,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,1 Convicted Criminal,ACTIVE,...,GUATEMALA,Male,NaN,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",1 Convicted Criminal,3.0,0032442e66899c8db1af57d2421d5fe8285525d4
568,2026-01-12 10:20:44,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,ECUADOR,Female,2026-01-15 00:00:00,2024-02-07 00:00:00,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,01db17dc0a64600d071f6cd8b5c06f9dd97d36b6
620,2026-02-22 08:13:24,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,VENEZUELA,Female,2026-02-24 00:00:00,2025-10-31 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,020523ae856b5f4288cb12ae3dc1af4d84b68eb9
627,2026-01-05 11:46:24,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,PERU,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,02101d733c35e324c074799f2fa8bdcd327d8211
677,2026-01-19 07:39:22,Collateral,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,3-Voluntary Departure Confirmed,...,MEXICO,Male,2026-01-22 00:00:00,NaN,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,023d885b31d6d0fc05fe98627036d2a3308ca032
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74771,2026-01-15 11:03:48,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f7a14c067221229f55e8b7d8bce43e53767e5698
74902,2026-02-25 12:34:30,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,MEXICO,Male,NaN,NaN,RENSSELAER COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f81b4bada2ea65590d56866019ee5c403bc5797d
75270,2026-03-06 11:51:24,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,ECUADOR,Female,NaN,2010-05-13 00:00:00,ALBANY COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,f946c2a321e916fd6065322d5a59aa68752952b3
75558,2026-01-20 13:36:14,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,8-Excluded/Removed - Inadmissibility,...,GUATEMALA,Male,2026-01-30 00:00:00,2023-06-14 00:00:00,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fa3cb4ff999a29d4f1cf4004ddf0223823690188
75924,2026-01-12 10:52:18,Targeted,NEW YORK,NaN,Buffalo Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,GUINEA,Male,NaN,NaN,SARATOGA COUNTY,NaN,"ERO - Albany, NY Sub-Office",3 Other Immigration Violator,NaN,fb57260c30e93cc6de984dd61ae4ae20470d82fa

In [16]:
df_CR["Apprehension Site Landmark"].value_counts()

SARATOGA COUNTY            55
ALBANY COUNTY              44
RENSSELAER COUNTY          13
SCHENECTADY COUNTY JAIL     3
WASHINGTON COUNTY JAIL      1
WARREN COUNTY               1
Name: Apprehension Site Landmark, dtype: int64

In [24]:
df_CR.to_csv('FilteredData/2026CapitalRegionICEArrests.csv', index = True)