In [1]:
## import necessary libraries
import pandas as pd

In [3]:
df = pd.read_excel('/Users/sajinashrestha/Documents/dataProjects/WAMC/ICE Arrests/RawData/2026-ICLI-00005_Arrests_FY24_20260311_Redacted.xlsx')

In [4]:
df

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
0,For Official Use Only (FOUO)/Pre-decisional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Deportation Data Project - 2026-ICLI-00005 - 0...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ERO Administrative Arrests FY2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113839,2024-09-29 21:18:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Non-Custodial Arrest,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,-,"ERO - LUBBOCK, TX SUB-OFFICE",NaN,NaN,NaN
113840,2024-09-29 16:25:00,NaN,TEXAS,NaN,Dallas Area of Responsibility,Fugitive Operations,ICE,Located,2 Pending Criminal Charges,NaN,...,MEXICO,Female,NaN,NaN,HOCKLEY COUNTY JAIL,NaN,"ERO - Amarillo, TX Sub-Office",NaN,NaN,NaN
113841,2024-09-30 09:57:48,NaN,NaN,NaN,NaN,Fugitive Operations,ICE,Inspections,3 Other Immigration Violator,NaN,...,JAMAICA,Female,NaN,NaN,NaN,NaN,"GALVESTON, TX, POE",NaN,NaN,NaN
113842,2024-09-30 08:17:47,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNKNOWN,Male,NaN,NaN,NaN,NaN,"NACO, AZ, POE",NaN,NaN,NaN
113843,2024-09-30 11:07:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2024-09-30 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN

In [ ]:
df.info()

In [15]:
df2 = df.iloc[5:]

In [16]:
df2

,ERO LESA Statistical Tracking Unit,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24
5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
6,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
7,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
8,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
9,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172938,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172939,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172940,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172941,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172942,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [17]:
df2.columns = df2.iloc[0]
df_titled = df2[1:].reset_index(drop=True)

In [18]:
df_titled

5,Apprehension Date,Apprehension Type,State,County,TOA Current Duty AOR,Apprehension Final Program,Arresting Agency,Apprehension Method,Apprehension Criminality,Case Status,...,Citizenship Country,Gender,Departed Date,Final Order Date,Apprehension Site Landmark,Operation,TOA Current Duty Site,Case Criminality,Case Threat Level,Anonymized Identifier
0,2022-10-05 11:08:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,VENEZUELA,Female,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002880c7d1c7fc09144a3fe22a5b45c5c204a6
1,2023-05-09 11:11:00,NaN,NEW YORK,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,NICARAGUA,Male,NaN,NaN,"NDD - 26 FEDERAL PLAZA NY, NY",-,"NEW YORK, NY, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00002d45a605af4dcf152d154a394bc4a8ac57c4
2,2023-01-12 09:53:00,NaN,NaN,NaN,San Francisco Area of Responsibility,ERO Criminal Alien Program,ICE,CAP State Incarceration,1 Convicted Criminal,6-Deported/Removed - Deportability,...,MEXICO,Male,2023-01-13 00:00:00,2019-07-25 00:00:00,"BKI GENERAL AREA, NON-SPECIFIC",NaN,"ERO - Bakersfield, CA IHP Sub Office",1 Convicted Criminal,1,00005ee8ff539795f2114c218f445634884d01e4
3,2023-08-22 16:07:00,NaN,NaN,NaN,Salt Lake City Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,8-Excluded/Removed - Inadmissibility,...,MEXICO,Male,2023-09-05 00:00:00,2023-08-23 00:00:00,CLARK COUNTY DETENTION CENTER,NaN,"LAS VEGAS, NV, DOCKET CONTROL OFFICE",1 Convicted Criminal,3,0000ee96b6cebdde068bf9d73f4473288c652188
4,2022-11-18 11:40:00,NaN,NEW JERSEY,NaN,Newark Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,ACTIVE,...,HAITI,Male,NaN,NaN,ICE ERO NEWARK,-,"NEWARK, NJ, DOCKET CONTROL OFFICE",3 Other Immigration Violator,NaN,00012138344f907502a4c08061b6793d9694f390
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
172932,2023-09-28 20:33:30,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,UNITED KINGDOM,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172933,2023-09-29 08:45:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,Law Enforcement Agency Response Unit,2 Pending Criminal Charges,9-VR Witnessed,...,MEXICO,Male,2023-09-29 00:00:00,NaN,"HLG GENERAL AREA, NON-SPECIFIC",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",2 Pending Criminal Charges,NaN,NaN
172934,2023-09-29 19:53:39,NaN,NaN,NaN,NaN,Detention and Deportation,ICE,Inspections,3 Other Immigration Violator,NaN,...,BRAZIL,Female,NaN,NaN,NaN,NaN,"HOUSTON, TX, POE",NaN,NaN,NaN
172935,2023-09-30 11:18:00,NaN,TEXAS,NaN,Harlingen Area of Responsibility,ERO Criminal Alien Program,ICE,CAP Local Incarceration,1 Convicted Criminal,9-VR Witnessed,...,MEXICO,Male,2023-09-30 00:00:00,NaN,"SEGOVIA STATE JAIL- PRE-RELEASE, TX",NaN,"HARLINGEN, TX, DOCKET CONTROL OFFICE",1 Convicted Criminal,1,NaN
172936,2023-05-03 05:00:00,Targeted,NEW JERSEY,NaN,New York City Area of Responsibility,Non-Detained Docket Control,ICE,Non-Custodial Arrest,3 Other Immigration Violator,NaN,...,UNKNOWN,Female,NaN,NaN,"XNY GENERAL AREA, NON-SPECIFIC",NaN,"NEW YORK, NY, DOCKET CONTROL OFFICE",NaN,NaN,NaN

In [35]:
## turn the column into datetime
df_titled['Apprehension Date'] = pd.to_datetime(df_titled['Apprehension Date'])

In [ ]:
df_titled

In [33]:
## create a subset of data for only 2025 and 2026 
df_2025 = df_titled[df_titled['Apprehension Date'] > '2025-01-20']

In [34]:
df_2025

Empty DataFrame
Columns: [Apprehension Date, Apprehension Type, State, County, TOA Current Duty AOR, Apprehension Final Program, Arresting Agency, Apprehension Method, Apprehension Criminality, Case Status, Case Category, Departure Country, Final Order Yes No, Birth Date, Birth Year, Citizenship Country, Gender, Departed Date, Final Order Date, Apprehension Site Landmark, Operation, TOA Current Duty Site, Case Criminality, Case Threat Level, Anonymized Identifier]
Index: []

In [26]:
## Which borough had the most crashes?
df_titled["State"].value_counts()

TEXAS                             29850
NEW YORK                          10785
NEW JERSEY                         9879
CALIFORNIA                         9370
FLORIDA                            7620
MASSACHUSETTS                      5846
COLORADO                           3311
TENNESSEE                          3300
ILLINOIS                           2639
LOUISIANA                          2590
WASHINGTON                         2446
ARIZONA                            2207
GEORGIA                            2114
OKLAHOMA                           2108
VIRGINIA                           2035
PENNSYLVANIA                       2022
NORTH CAROLINA                     2022
MARYLAND                           1816
OHIO                               1789
SOUTH CAROLINA                     1674
MISSISSIPPI                        1507
WISCONSIN                          1420
UTAH                               1360
NEBRASKA                           1331
ALABAMA                            1290
MICHIGAN                           1256
ARKANSAS                           1230
INDIANA                            1196
MINNESOTA                          1083
MAINE                               885
KENTUCKY                            840
MISSOURI                            801
KANSAS                              665
IOWA                                656
NEVADA                              535
RHODE ISLAND                        432
PUERTO RICO                         370
NEW HAMPSHIRE                       354
WEST VIRGINIA                       324
IDAHO                               243
WYOMING                             195
DELAWARE                            186
OREGON                              181
NEW MEXICO                          156
CONNECTICUT                         151
MONTANA                             113
SOUTH DAKOTA                        111
ALASKA                               61
VERMONT                              57
NORTH DAKOTA                         51
HAWAII                               50
DISTRICT OF COLUMBIA                 31
VIRGIN ISLANDS                       18
NORTHERN MARIANA ISLANDS             15
GUAM                                  9
ARMED FORCES - THE AMERICAS           6
FEDERATED STATES OF MICRONESIA        2
ARMED SERVICES - PACIFIC              1
Name: State, dtype: int64